dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libsfml-dev
script:
  - ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CXX=g++-7
  - g++ -v && cmake --version
  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake ..
  - make
  - ./test_qwertyattack
  

