dist: xenial
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - freeglut3-dev
      - libxrandr-dev
      - libudev-dev
      - libopenal-dev
      - libflac-dev
      - libvorbis-dev
      - g++-7

before_script:
  - export CXX=g++-7
  - g++ -v && cmake --version
  - git clone https://github.com/sfml/sfml && cd sfml
  - git checkout tags/2.5.1
  - mkdir build && cd build
  - cmake ..
  - sudo cmake --build . --target install
  - cd ../..
script:
  - mkdir cmake-build-release && cd cmake-build-release
  - cmake ..
  - make
  - ./test_qwertyattack


